### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by wimjongman** [lcaron/SWT-OldSchoolEffect#1]
Really cool Laurent. Thanks.

I found two issues. 

1. The project is referencing a resource folder. It is not there and the project has an error. I removed the reference and all is fine.

2. SineScroll.java image is missing. Replace the code on line 251 with:

		String file = getClass().getResource("font_classic_16x16.gif").getFile();
		final Image img = new Image(Display.getCurrent(), file);

**Comment by lcaron** [comment]
Thank you for your feedback, the bugs have been fixed.
