### ISSUE TITLE
Not working in Linux

### ISSUE THREAD

**Issue by vogella** [lcaron/SWT-OldSchoolEffect#2]
I tried the examples on Linux but I only get a empty window.

![image](https://user-images.githubusercontent.com/139910/70045531-8f4a3580-15c4-11ea-850a-954d4f8fd830.png)

**Comment by lcaron** [comment]
Hi Lars,
Thank you for your feedback. To be honest I have only tested the screens on Windows, but I'll have a look on Linux.

**Comment by vogella** [comment]
Thanks.

**Comment by vogella** [comment]
Steps I did:

Removed the hard-coded SWT version from the .classpath
Converted Java project to plug-in project
Add SWT from my Eclipse installation as dependency
Tried several examples

**Comment by lcaron** [comment]
Hi Lars
I've updated the source code, so it runs now on both Windows (tested on Windows 10) and Linux (tested on Fedora with Wayland).
